### ISSUE TITLE
Error: Screening orfs vs PHROGs HMM files

### ISSUE THREAD

**Issue by JLammons14** [Chrisjrt/hafeZ#8]
Thanks for making the tool. This is my first time using the hafez and I have been running into this error:

'could not open file 'hageZ_db/phrogs_hhsuite_db/phrogs_cs219.ffdata'

the error is coming from the line here:
FileNotFoundError: [Errno 2] No such file or directory: '/home/hafez/hafeZ-master/output/temp_roi_1000_c1~orf_1.tab'
"""
I'm not sure why this is occurring, but we have identified phage in this sample using Vibrant and by mapping contigs to the refseq database. 

Also here is the command I used
./hafeZ.py -f S32_final_contigs.fasta -r1 S32_L003_R1_001.fastq.gz -r2 S32_L003_R2_001.fastq.gz -o output -D hageZ_db -T phrogs

**Comment by Chrisjrt** [comment]
Hey, 

So this error is basically saying that hafeZ can't find the PHROGs reference database (which I assume you've already setup). 

I think the error might just be due to a typo, as in your command you've got '-D hageZ_db' (g instead of f) and I'm going to guess you actually called your folder 'hafeZ_db'. 

So run this and it should hopefully now work:

`./hafeZ.py -f S32_final_contigs.fasta -r1 S32_L003_R1_001.fastq.gz -r2 S32_L003_R2_001.fastq.gz -o output -D hafeZ_db -T phrogs`

Let me know if this fixes the issue 😊
